# Setting Directory
> getwd()
[1] "C:/Users/FARZAD/Documents"
> setwd("C:/Users/FARZAD/Desktop/Data Science/Course 5")
> getwd()
[1] "C:/Users/FARZAD/Desktop/Data Science/Course 5"
library(lubridate)
library(ggplot2) 
library(Hmisc)
# reading Data
> if(!file.exists('activity.csv')){
+     unzip('activity.zip')
+ }
# Calculating activity data
#Calculating steps per day
> activityData <- read.csv('activity.csv')
> stepsByDay <- tapply(activityData$steps, activityData$date, sum, na.rm=TRUE)
#Histogram total step per day
> ggplot(data=averageStepsPerTimeBlock, aes(x=interval, y=meanSteps)) +
+     geom_line() +
+     xlab("5-minute interval") +
+     ylab("average number of steps taken")
> mostSteps <- which.max(averageStepsPerTimeBlock$meanSteps)
> timeMostSteps <-  gsub("([0-9]{1,2})([0-9]{2})", "\\1:\\2", averageStepsPerTimeBlock[mostSteps,'interval'])
> timeMostSteps
[1] "8:35"
> mostSteps
[1] 104
# Evaluation of missing data
> numMissingValues <- length(which(is.na(activityData$steps)))
> numMissingValues
[1] 2304
> activityDataImputed <- activityData
> activityDataImputed$steps <- impute(activityData$steps, fun=mean)
> stepsByDayImputed <- tapply(activityDataImputed$steps, activityDataImputed$date, sum)
> qplot(stepsByDayImputed, xlab='Total steps per day (Imputed)', ylab='Frequency using binwith 300', binwidth=300)
#calculating mean & Median of total step per day
> stepsByDayMeanImputed <- mean(stepsByDayImputed)
> stepsByDayMedianImputed <- median(stepsByDayImputed)
> activityDataImputed$dateType <-  ifelse(as.POSIXlt(activityDataImputed$date)$wday %in% c(0,6), 'weekend', 'weekday')
#calculating average daily activity 
> averagedActivityDataImputed <- aggregate(steps ~ interval + dateType, data=activityDataImputed, mean)
# Histogram Average daily activity
> ggplot(averagedActivityDataImputed, aes(interval, steps)) + 
+     geom_line() + 
+     facet_grid(dateType ~ .) +
+     xlab("5-minute interval") + 
+     ylab("avarage number of steps")
